### ISSUE TITLE
CXXFLAGS must come after objects in Makefile binary rule

### ISSUE THREAD

**Issue by ahbarnett** [dmalhotra/CSBQ#3]
[Hi Dhairya - hope it's ok if I use Issues to document fixes. This one's for the Makefile.

After getting frustrated with dgemm_ being undefined symbol even though I had -lblas in the CXXFLAGS,
I realised the library flags have to come *after* the object files. So, the binary make task should be:

```
$(BINDIR)/%: $(OBJDIR)/%.o
	-@$(MKDIRS) $(dir $@)
	$(CXX) $^ $(LDLIBS) -o $@ $(CXXFLAGS)
```
Now it works for me.

PS happy new year!

**Comment by dmalhotra** [comment]
That makes sense, but I'm not sure why I haven't run into this issue.
Thanks for the fix.. I've pulled the changes from your fork.

Happy new year!
